/*
 * generated by Xtext
 */
package org.eclipse.viatra2.patternlanguage.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EMFPatternLanguageUiModule extends org.eclipse.viatra2.patternlanguage.ui.AbstractEMFPatternLanguageUiModule {
	public EMFPatternLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
