/*
* generated by Xtext
*/
package org.eclipse.viatra2.patternlanguage;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class EMFPatternLanguageUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.eclipse.viatra2.patternlanguage.ui.internal.EMFPatternLanguageActivator.getInstance().getInjector("org.eclipse.viatra2.patternlanguage.EMFPatternLanguage");
	}
	
}
