/*
* generated by Xtext
*/
package org.eclipse.viatra2.patternlanguage.ui.contentassist;

import org.eclipse.viatra2.patternlanguage.ui.contentassist.AbstractEMFPatternLanguageProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class EMFPatternLanguageProposalProvider extends AbstractEMFPatternLanguageProposalProvider {

}
