/*
* generated by Xtext
*/
package org.eclipse.incquery.tooling.generator.model.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class GeneratorModelOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
