/*
 * generated by Xtext
 */
package org.eclipse.viatra2.patternlanguage;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EMFPatternLanguageRuntimeModule extends org.eclipse.viatra2.patternlanguage.AbstractEMFPatternLanguageRuntimeModule {

}
