/*
 * generated by Xtext
 */
package org.eclipse.viatra2.patternlanguage.core;

import org.eclipse.viatra2.patternlanguage.core.scoping.PatternLanguageLinkingService;
import org.eclipse.xtext.linking.ILinkingService;
import org.eclipse.xtext.naming.IQualifiedNameConverter;
import org.eclipse.xtext.xtext.XtextQualifiedNameConverter;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PatternLanguageRuntimeModule extends AbstractPatternLanguageRuntimeModule {

	public Class<? extends IQualifiedNameConverter> bindIQualifiedNameConverter() {
		return XtextQualifiedNameConverter.class;
	}
	
	@Override
	public Class<? extends ILinkingService> bindILinkingService() {
		return PatternLanguageLinkingService.class;
	}
}
