<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="EIQSnapshot"
    nsURI="http://www.eclipse.org/viatra2/emf/incquery/snapshot" nsPrefix="eiqSnapshot">
  <eClassifiers xsi:type="ecore:EClass" name="MatchSetRecord">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="patternQualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="matches" ordered="false"
        upperBound="-1" eType="#//MatchRecord" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filter" eType="#//MatchRecord"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatchRecord">
    <eStructuralFeatures xsi:type="ecore:EReference" name="substitutions" upperBound="-1"
        eType="#//MatchSubstitutionRecord" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" eType="#//RecordRole"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatchSubstitutionRecord" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameterName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derivedValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMFSubstitution" eSuperTypes="#//MatchSubstitutionRecord">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntSubstitution" eSuperTypes="#//MatchSubstitutionRecord">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LongSubstitution" eSuperTypes="#//MatchSubstitutionRecord">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoubleSubstitution" eSuperTypes="#//MatchSubstitutionRecord">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FloatSubstitution" eSuperTypes="#//MatchSubstitutionRecord">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanSubstitution" eSuperTypes="#//MatchSubstitutionRecord">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringSubstitution" eSuperTypes="#//MatchSubstitutionRecord">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DateSubstitution" eSuperTypes="#//MatchSubstitutionRecord">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumSubstitution" eSuperTypes="#//MatchSubstitutionRecord">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueLiteral" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumType" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MiscellaneousSubstitution" eSuperTypes="#//MatchSubstitutionRecord">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IncQuerySnapshot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="matchSetRecords" upperBound="-1"
        eType="#//MatchSetRecord" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelRoots" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inputSpecification" eType="#//InputSpecification"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InputSpecification">
    <eLiterals name="Unset" value="-1" literal="Unset"/>
    <eLiterals name="ResourceSet"/>
    <eLiterals name="Resource" value="1"/>
    <eLiterals name="EObject" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RecordRole">
    <eLiterals name="Match"/>
    <eLiterals name="Filter" value="1" literal="Filter"/>
  </eClassifiers>
</ecore:EPackage>
