/*
 * generated by Xtext
 */
package org.eclipse.viatra2.patternlanguage.scoping;

import org.eclipse.viatra2.patternlanguage.core.scoping.PatternLanguageScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class EMFPatternLanguageScopeProvider extends PatternLanguageScopeProvider {

}
