/*
* generated by Xtext
*/
package org.eclipse.viatra2.patternlanguage.core;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class PatternLanguageUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.eclipse.viatra2.patternlanguage.core.ui.internal.PatternLanguageActivator.getInstance().getInjector("org.eclipse.viatra2.patternlanguage.core.PatternLanguage");
	}
	
}
