/*
 * generated by Xtext
 */
package org.eclipse.viatra2.patternlanguage.core.scoping;

import org.eclipse.xtext.xbase.scoping.XbaseScopeProvider;

/**
 * This class contains custom scoping description. The scoping related to metamodel elements is based on the code from {@link org.eclipse.xtext.xtext.XtextScopeProvider}.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 * @author Zoltan Ujhelyi
 */
@SuppressWarnings("all")
public class PatternLanguageScopeProvider extends XbaseScopeProvider {

	
}
