/*
* generated by Xtext
*/
package org.eclipse.viatra2.gtasm.ui.contentassist;

import static org.eclipse.emf.ecore.util.EcoreUtil.getRootContainer;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EClassifier;
import org.eclipse.emf.ecore.EDataType;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.jface.text.Region;
import org.eclipse.jface.text.contentassist.ICompletionProposal;
import org.eclipse.viatra2.gtasm.patternLanguage.EMFType;
import org.eclipse.viatra2.gtasm.patternLanguage.Import;
import org.eclipse.viatra2.gtasm.patternLanguage.Parameter;
import org.eclipse.viatra2.gtasm.patternLanguage.PatternModel;
import org.eclipse.viatra2.gtasm.patternLanguage.Variable;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.naming.IQualifiedNameConverter;
import org.eclipse.xtext.naming.QualifiedName;
import org.eclipse.xtext.nodemodel.ICompositeNode;
import org.eclipse.xtext.nodemodel.ILeafNode;
import org.eclipse.xtext.nodemodel.util.NodeModelUtils;
import org.eclipse.xtext.resource.EObjectDescription;
import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.ui.editor.contentassist.ConfigurableCompletionProposal;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;
import org.eclipse.xtext.ui.editor.contentassist.PrefixMatcher;

import com.google.common.base.Function;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class PatternLanguageProposalProvider extends AbstractPatternLanguageProposalProvider {

	public static class ClassifierPrefixMatcher extends PrefixMatcher {
		private PrefixMatcher delegate;

		private IQualifiedNameConverter qualifiedNameConverter;

		public ClassifierPrefixMatcher(PrefixMatcher delegate, IQualifiedNameConverter qualifiedNameConverter) {
			this.delegate = delegate;
			this.qualifiedNameConverter = qualifiedNameConverter;
		}

		@Override
		public boolean isCandidateMatchingPrefix(String name, String prefix) {
			if (delegate.isCandidateMatchingPrefix(name, prefix))
				return true;
			QualifiedName qualifiedName = qualifiedNameConverter.toQualifiedName(name);
			QualifiedName qualifiedPrefix = qualifiedNameConverter.toQualifiedName(prefix);
			if (qualifiedName.getSegmentCount() > 1) {
				if (qualifiedPrefix.getSegmentCount() == 1)
					return delegate.isCandidateMatchingPrefix(qualifiedName.getSegment(1),
							qualifiedPrefix.getFirstSegment());
				if (!delegate.isCandidateMatchingPrefix(qualifiedName.getFirstSegment(),
						qualifiedPrefix.getFirstSegment()))
					return false;
				return delegate.isCandidateMatchingPrefix(qualifiedName.getSegment(1), qualifiedPrefix.getSegment(1));
			}
			return false;
		}

	}
	
	@Override
	public void completeType_Typename(EObject model, Assignment assignment, ContentAssistContext context, ICompletionProposalAcceptor acceptor) {
		PatternModel pModel = null;
		EObject root = getRootContainer(model);
		if (root instanceof PatternModel){
			pModel = (PatternModel) root;
		}
		ContentAssistContext.Builder myContextBuilder = context.copy();
		myContextBuilder.setMatcher(new ClassifierPrefixMatcher(context.getMatcher(), getQualifiedNameConverter()));
		EMFType type = null;
		if (model instanceof Variable) {
			type = ((Variable) model).getType();
		} else {
			return;
		}
		
		ICompositeNode node = NodeModelUtils.getNode(type);
		int offset = node.getOffset();
		Region replaceRegion = new Region(offset, context.getReplaceRegion()
				.getLength() + context.getReplaceRegion().getOffset() - offset);
		myContextBuilder.setReplaceRegion(replaceRegion);
		myContextBuilder.setLastCompleteNode(node);
		StringBuilder availablePrefix = new StringBuilder(4);
		for (ILeafNode leaf : node.getLeafNodes()) {
			if (leaf.getGrammarElement() != null && !leaf.isHidden()) {
				if ((leaf.getTotalLength() + leaf.getTotalOffset()) < context
						.getOffset())
					availablePrefix.append(leaf.getText());
				else
					availablePrefix.append(leaf.getText().substring(0,
							context.getOffset() - leaf.getTotalOffset()));
			}
			if (leaf.getTotalOffset() >= context.getOffset())
				break;
		}
		myContextBuilder.setPrefix(availablePrefix.toString());
		
		ContentAssistContext myContext = myContextBuilder.toContext();
		for (Import declaration : pModel.getImports()) {
			if (declaration.getEPackage() != null) {
				createClassifierProposals(declaration, model, myContext, acceptor);
			}
		}
	}
	
	private void createClassifierProposals(Import declaration, EObject model,
			ContentAssistContext context, ICompletionProposalAcceptor acceptor) {
		//String alias = declaration.getAlias();
		//QualifiedName prefix = (!Strings.isEmpty(alias)) 
		//	? QualifiedName.create(getValueConverter().toString(alias,"ID")) 
		//	: null;
		boolean createDatatypeProposals = modelOrContainerIs(model, Parameter.class);
		boolean createEnumProposals = modelOrContainerIs(model, EnumRule.class);
		boolean createClassProposals = modelOrContainerIs(model, Parameter.class);
		Function<IEObjectDescription, ICompletionProposal> factory = getProposalFactory(null, context);
		for (EClassifier classifier : declaration.getEPackage().getEClassifiers()) {
			if (classifier instanceof EDataType && createDatatypeProposals || classifier instanceof EEnum
					&& createEnumProposals || classifier instanceof EClass && createClassProposals) {
				String classifierName = getValueConverter().toString(classifier.getName(), "ID");
				QualifiedName proposalQualifiedName = /*(prefix != null) ? prefix.append(classifierName) :*/ QualifiedName
						.create(classifierName);
				System.out.println(proposalQualifiedName);
				IEObjectDescription description = EObjectDescription.create(proposalQualifiedName, classifier);
				ConfigurableCompletionProposal proposal = (ConfigurableCompletionProposal) factory.apply(description);
				if (proposal != null) {
					/*if (prefix != null)
						proposal.setDisplayString(classifier.getName() + " - " + alias);*/
					proposal.setPriority(proposal.getPriority() * 2);
				}
				acceptor.accept(proposal);
			}
		}
	}
	
	private boolean modelOrContainerIs(EObject model, Class<?>... types) {
		for (Class<?> type : types) {
			if (type.isInstance(model) || type.isInstance(model.eContainer()))
				return true;
		}
		return false;
	}
}
