/*
* generated by Xtext
*/
package org.eclipse.viatra2.emf.incquery.tooling.generator.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class GeneratorModelOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
