<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="incquerygenmodel"
    nsURI="http://incquerygenmodel/1.0" nsPrefix="incquerygenmodel">
  <eClassifiers xsi:type="ecore:EClass" name="IncQueryGenmodel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ecoreModel" upperBound="-1"
        eType="#//EcoreModel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EcoreModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="models" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.codegen.ecore/model/GenModel.ecore#//GenModel"/>
  </eClassifiers>
</ecore:EPackage>
