/*
 * generated by Xtext
 */
package org.eclipse.viatra2.emf.incquery.tooling.generator.mavenbuilder;

import org.eclipse.viatra2.emf.incquery.tooling.generator.IncQueryGeneratorPlugin;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MavenBuilderExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return IncQueryGeneratorPlugin.INSTANCE.getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return IncQueryGeneratorPlugin.INSTANCE.getInjector();
	}
	
}
