/*
 * generated by Xtext
 */
package org.eclipse.viatra2.gtasm.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PatternLanguageUiModule extends org.eclipse.viatra2.gtasm.ui.AbstractPatternLanguageUiModule {
	public PatternLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
