/*
 * generated by Xtext
 */
package org.eclipse.incquery.tooling.generator.model.ui.contentassist;

import org.eclipse.incquery.tooling.generator.model.ui.contentassist.AbstractGeneratorModelProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class GeneratorModelProposalProvider extends AbstractGeneratorModelProposalProvider {

}
