/*
* generated by Xtext
*/
package org.eclipse.viatra2.emf.incquery.tooling.generator.ui.contentassist;

import org.eclipse.viatra2.emf.incquery.tooling.generator.ui.contentassist.AbstractGeneratorModelProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class GeneratorModelProposalProvider extends AbstractGeneratorModelProposalProvider {

}
