/*
* generated by Xtext
*/
package org.eclipse.viatra2.gtasm.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class PatternLanguageOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
