/*
 * generated by Xtext
 */
package org.eclipse.viatra2.emf.incquery.tooling.generator;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GeneratorModelRuntimeModule extends org.eclipse.viatra2.emf.incquery.tooling.generator.AbstractGeneratorModelRuntimeModule {

}
